sqlite3 sample.db ".read sql/create.sql"
sqlite3 sample.db ".separator |"
sqlite3 sample.db ".import ../dat/User.dat User"
sqlite3 sample.db "UPDATE User SET location = null WHERE location = 'None'"
sqlite3 sample.db "UPDATE User SET country = null WHERE country = 'None'"
sqlite3 sample.db ".import ../dat/Item.dat Item"
sqlite3 sample.db "UPDATE Item SET Buy_Price = null WHERE Buy_Price = 'None'"
sqlite3 sample.db ".import ../dat/Category.dat Category"
sqlite3 sample.db ".import ../dat/Bids.dat Bids"